pipeline {
    agent any
    tools {nodejs "node1415"}

    environment {
        DOCKER_IMAGE = "springboot-jpa-school"
        TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGENAME = "${DOCKER_IMAGE}:${TAG}"
        NODEPORT = "31112"
        NAMESPACE = "myproject"
        APP_NAME = "myproject-school-frontend"
    }

    stages {
        stage('yarn install&build'){
            steps{
                dir('frontend'){
                    sh 'yarn install'
                    sh 'yarn build'
                }
            }
        }
        stage('docker build&push'){
            steps{
                dir('frontend'){
                    sh 'cp cicd/* ./'
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        script{
                            sh 'docker build -t ${dockerID}/${DOCKER_IMAGENAME} .'
                            withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerpassword', usernameVariable: 'dockeruser')]) {
                                sh 'docker login -u ${dockeruser} -p ${dockerpassword}'
                                sh 'docker push ${dockerID}/${DOCKER_IMAGENAME}'
                            }
                        }
                    }
                }
            }
        }
        stage('deploy'){
            steps{
                dir('frontend'){
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        sh 'sed -i "s/__IMAGE_NAME__/${dockerID}\\/${DOCKER_IMAGENAME}/g" kubernetes-deploy.yaml'
                        sh 'sed -i "s/__NAMESPACE__/${NAMESPACE}/g" kubernetes-deploy.yaml'
                        sh 'sed -i "s/__NODEPORT__/${NODEPORT}/g" kubernetes-deploy.yaml'
                        sh 'kubectl apply -f kubernetes-deploy.yaml'
                        sh 'kubectl rollout restart deployment -n ${NAMESAPCE} ${APP_NAME}'
                    }
                }
            }
        }
    }
}